# Generated by Django 5.0.2 on 2026-02-20 21:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrun',
            name='attempt',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jobrun',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=160, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='jobrun',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='jobrun',
            name='mode',
            field=models.CharField(choices=[('amocrm_radist', 'amoCRM + Radist'), ('radist_only', 'Radist only'), ('amocrm_only', 'amoCRM only')], default='amocrm_radist', max_length=24),
        ),
        migrations.AddField(
            model_name='jobrun',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_job_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobrun',
            name='trigger_type',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual'), ('system', 'System')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='jobrun',
            name='window_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrun',
            name='window_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='followup_deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='job_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='core.jobrun'),
        ),
        migrations.AddField(
            model_name='report',
            name='window_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='window_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TenantRuntimeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('amocrm_radist', 'amoCRM + Radist'), ('radist_only', 'Radist only'), ('amocrm_only', 'amoCRM only')], default='amocrm_radist', max_length=24)),
                ('timezone', models.CharField(default='Asia/Almaty', max_length=64)),
                ('business_day_start', models.TimeField(default=datetime.time(22, 1))),
                ('scheduled_run_time', models.TimeField(default=datetime.time(22, 10))),
                ('is_schedule_enabled', models.BooleanField(default=True)),
                ('radist_fetch_limit', models.PositiveIntegerField(default=200)),
                ('min_dialogs_for_report', models.PositiveIntegerField(default=1)),
                ('max_force_lookback_days', models.PositiveSmallIntegerField(default=3)),
                ('max_force_window_hours', models.PositiveSmallIntegerField(default=24)),
                ('telegram_followup_minutes', models.PositiveSmallIntegerField(default=60)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='runtime_config', to='core.tenant')),
            ],
            options={
                'ordering': ['tenant_id'],
            },
        ),
    ]
