# Generated by Django 5.0.2 on 2026-02-20 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jobrun_attempt_jobrun_idempotency_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRunEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warn', 'Warn'), ('error', 'Error')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.jobrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
